

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,trace,logfile,prometheus,threaddump
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true

  observations:
    annotations:
      enabled: true




  tracing:
    export:
      enabled: true
      otlp:
        enabled: true
    propagation:
      consume: W3C, B3, B3_MULTI
      produce: W3C, b3, b3_multi
      type: w3c, b3_multi, b3
    sampling:
      probability: 1.0


  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        all: true
      percentiles:
        all: 0.99, 0.95, 0.90, 0.75
    data:
      repository:
        autotime:
          enabled: true
          percentiles-histogram: true
          percentiles: 0.99, 0.95


  logging:
    export:
      enabled: true
      otlp:
        enabled: true





  opentelemetry:

    logging:
      export:
        otlp:
          transport: http
          compression: gzip
          endpoint: https://otlp-gateway-prod-ap-south-1.grafana.net/otlp/v1/logs
#          endpoint: http://192.168.1.93:4318/v1/logs
          headers:
            Authorization: "Basic MTAyMDYxOTpnbGNfZXlKdklqb2lNVEl3TlRRMk1TSXNJbTRpT2lKemRHRmpheTB4TURJd05qRTVMVzkwYkhBdGQzSnBkR1V0YjNSc2NDMWpiMjV1WldOMGIzSWlMQ0pySWpvaVFVeEdTRkJOT1ZZMldUaGFPRGcwUVRNd2NFWTJPRVZFSWl3aWJTSTZleUp5SWpvaWNISnZaQzFoY0MxemIzVjBhQzB4SW4xOQ=="


    tracing:
      export:
        otlp:
          transport: http
          compression: gzip
          endpoint: https://otlp-gateway-prod-ap-south-1.grafana.net/otlp/v1/traces
          headers:
            Authorization: "Basic MTAyMDYxOTpnbGNfZXlKdklqb2lNVEl3TlRRMk1TSXNJbTRpT2lKemRHRmpheTB4TURJd05qRTVMVzkwYkhBdGQzSnBkR1V0YjNSc2NDMWpiMjV1WldOMGIzSWlMQ0pySWpvaVFVeEdTRkJOT1ZZMldUaGFPRGcwUVRNd2NFWTJPRVZFSWl3aWJTSTZleUp5SWpvaWNISnZaQzFoY0MxemIzVjBhQzB4SW4xOQ=="
        include-unsampled: true



  otlp:
    metrics:
      export:
        enabled: true
        url: https://otlp-gateway-prod-ap-south-1.grafana.net/otlp/v1/metrics
        headers:
          Authorization: "Basic MTAyMDYxOTpnbGNfZXlKdklqb2lNVEl3TlRRMk1TSXNJbTRpT2lKemRHRmpheTB4TURJd05qRTVMVzkwYkhBdGQzSnBkR1V0YjNSc2NDMWpiMjV1WldOMGIzSWlMQ0pySWpvaVFVeEdTRkJOT1ZZMldUaGFPRGcwUVRNd2NFWTJPRVZFSWl3aWJTSTZleUp5SWpvaWNISnZaQzFoY0MxemIzVjBhQzB4SW4xOQ=="
        histogram-flavor: explicit-bucket-histogram
        aggregation-temporality: cumulative


#    logging:
#      export:
#        enabled: true
#    tracing:
#      export:
#        enabled: true










spring:



# redis
  data:
    redis:
      host: redis://enabling-molly-40932.upstash.io:6379
      port: 24981
      password: ${REDIS_PASSWORD}
      username: default
      client-type: Lettuce
      database: 0
      ssl:
        enabled: true



  # postgres
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://ep-little-darkness-ao35vpop-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate      # for development, use 'validate' or 'none' for production
    show-sql: true           # optional: shows SQL in logs
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.format_sql: true



#  cache:
#    type: caffeine





  rabbitmq:
    host: coral-01.rmq3.cloudamqp.com
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    # Optional: connection settings
    virtual-host: /
    connection-timeout: 60000

    # Publisher confirms & returns (useful for reliability)
    publisher-confirm-type: correlated
    publisher-returns: true

    # Listener container config
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10
      direct:
        acknowledge-mode: manual




weather:
  apikey: ${OPEN_WEATHER_API_KEY:0c3c357cbb2ceacfc2544131a21c4cdd}


logging:
  level:
    io.opentelemetry.exporter: DEBUG
#    io.micrometer: DEBUG
#server:
#  tomcat:
#    relaxed-query-chars: "[,],{,},|"
#    relaxed-path-chars: "[,],{,},|"


server:
  port: 8080



resilience4j:
  circuitbreaker:
    instances:
      openWeatherMap:
        failure-rate-threshold: 4
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2



springdoc:
  api-docs: # Custom API documentation endpoints
    path: /api-docs
  swagger-ui:
    enabled: true
    persist-authorization: true
    with-credentials: true
    oauth:
      client-id:
      client-secret:
      realm:
      app-name:




